### PR TITLE
pass a dict object to requests.put/post instead of a string

### PR DESCRIPTION
**Pull request by insatomcat**
see issue #39

### CODE REVIEW

**Comment by rymurr** [comment]
hey @insatomcat this will break the python client. The python client sends dict objects to `endpoints.py` already.

You can either:
1) update `cli.py` to translate the correct strings into objects 
or
2) check inside of `post` and `put` calls if the string is already an object or a string and convert appropriately. 

This part of the code is sorely lacking in testing too so its very easy to break stuff

**Comment by insatomcat** [comment]
Ok I find solution 2 quicker and cleaner (only 2 functions to change, and it will work even when the clients are extended with new features).
See the new commit.
Thanks.

**Comment by rymurr** [comment]
looks good to me, just fixed formatting and waiting for https://travis-ci.org/github/rymurr/dremio_client/builds/672576767 to pass

**Comment by insatomcat** [comment]
thanks, looks good to me

**Pull request merged**
