### PR TITLE
Remove HTML encoding of path

### PR DESCRIPTION
**Pull request by insatomcat**
Where querying dremio using HTTPS, current code works fine.

However when querying:
- dremio using HTTP
- with the dremio_client utility
- with a path and not a cid

Then, I get this error : 

```
# dremio_client catalog-item BDF.example_bug_round
Traceback (most recent call last):
  File "/usr/local/bin/dremio_client", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/cli.py", line 181, in catalog_item
    x = _catalog_item(token, base_url, cid, [i.replace(".", "/") for i in path] if path else None, ssl_verify=verify,)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/endpoints.py", line 99, in catalog_item
    return _get(base_url + "/api/v3/catalog{}".format(endpoint), token, idpath, ssl_verify=ssl_verify)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/endpoints.py", line 44, in _get
    return _check_error(r, details)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/endpoints.py", line 77, in _check_error
    raise DremioNotFoundException("No entity exists at " + details, error)
dremio_client.error.DremioNotFoundException: No entity exists at , BDF/example_bug_round: 404 Client Error: Not Found for url: http://xxxx:81/api/v3/catalog/by-path/BDF%2Fexample_bug_round
```

If I remove the HTML conversion then it solves the problem, and it still works with HTTPS...
I don't know why this conversion was here in the first place.

And I still haven't found why this fails only with HTTP and not HTTPS...

### CODE REVIEW

**Comment by rymurr** [comment]
This url encoding is required as per the docs: https://docs.dremio.com/rest-api/catalog/get-catalog-path.html (see the last line in the Syntax section).

because we are using '/' to separate the catalog parts and '/' is a valid character in a catalog path we have to escape '/' if its in the path.
in Dremio:
`space.folder."sub/folder"` is valid but `api/v3/catalog/by-path/space/folder/sub/folder` isn't so we have to used `api/v3/catalog/by-path/space/folder/sub%2Ffolder` .

I think the right way to fix this bug is to change:
`cpath = [i.replace("/", "%2F") for i in path] if path else ""` 
for
`cpath = [quote(i, safe='') for i in path] if path else ""`
where `quote` is from six (`from six.moves.urllib.parse import quote`)

**Comment by insatomcat** [comment]
Hello,

I think there are different issues here.

1) the encoding of the "/" is incomplete, the documentation state "?" as an example and indeed I see nowhere in the code where "?" would be encoded.
Your code suggestion would fix this I think.

2) The cli.py is sending ```path``` as a string to ```catalog_item``` in endpoints.py, but ```catalog_item``` expect a list of "parts".
I think the ```[i.replace(".", "/") for i in path]``` changes all '.' for '/' so when I submit ```dremio_client catalog-item BDF.test/test```, ```catalog_item```receives ```['BDF/test/test']```and then transform it to ```['BDF%2Ftest%2Ftest']```
Right now the CLI makes no difference of "." or "/", everything becomes a "/" that will soon be encoded to %2F.
I guess we should force the use of quotes to specify path name, since even "test.test" is a valid item name, but quotes in the command line seem to me managed by click so that can be tricky

3) It does not seem to be working with the python client either:

```
In [4]: a = catalog.BDF."test.test"
  File "<ipython-input-4-f467a2f38e2d>", line 1
    a = catalog.BDF."test.test"
                    ^
SyntaxError: invalid syntax


In [5]: a = catalog.BDF."test/test"
  File "<ipython-input-5-bbe9b30befd7>", line 1
    a = catalog.BDF."test/test"
                    ^
SyntaxError: invalid syntax


In [6]: a = catalog.BDF.test/test
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-a9b1142657e9> in <module>
----> 1 a = catalog.BDF.test/test

NameError: name 'test' is not defined```

**Comment by rymurr** [comment]
ahh, i think this is where documentation needs work. Try: `dremio_client catalog-item BDF test/test`. To get around the problem you describe above I enforce spaces between parts of the catalog path.

Also for the example above in python:
`a = catalog.BDF["test.test']` or `a = catalog['BDF']['test/test']` will work the catalog is a dict with overloads on `getattr` to enable the member reference style (and <tab> completion in notebooks)

**Comment by insatomcat** [comment]
Oh indeed that's a better solution :)
I've commited your "quote" proposal in this PR, in case you want to merge this part.

Note that ```a = catalog.BDF["test.test']``` does not work, in fact the "test.test" does not even show in the list of childs ...

**Comment by insatomcat** [comment]
oh I just saw you already made the change. Cool.

**Comment by rymurr** [comment]
hey @insatomcat I was fixing up some stuff for a release so I thought i would incorporate your change. Note I just released `0.11.1` with all your fixes in it.

**Pull request closed without merging**
